image: node:latest

services:
  - postgres:15.1-alpine

variables:
  POSTGRES_DB: poca-db
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: password
  POSTGRES_HOST_AUTH_METHOD: trust

stages:
  - build

build:
  stage: build
  script:
    - cd apps/api
    - npm install
    - npm run build
    - mv .env.gitlab .env
    - yarn db:migrate
    - npm run test
